# Generated by Django 6.0.3 on 2026-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.AddField(
            model_name='word',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learn', 'Learn'), ('know', 'Know')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='word',
            name='times_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
