# Generated by Django 6.0.3 on 2026-03-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_word_options_remove_word_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='status',
        ),
    ]
